name = "telegram-sheet-broadcast-worker"
main = "src/worker.js"
compatibility_date = "2026-05-09"

[triggers]
crons = ["*/2 * * * *"]

[[kv_namespaces]]
binding = "SHEET_STATE_KV"
id = "PUT_YOUR_KV_NAMESPACE_ID_HERE"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true
